name: Build
on:
  push:
    branches: [ master, actions ]
  pull_request:
    branches: [ master, actions ]

jobs:
  # WINDOWS x64 MSVC
  build:
    name: Build
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: windows-latest
            name: "Windows x64 MSVC"
            artifact: "Windows-MSVC.tar.xz"
            build_type: "RelWithDebInfo"
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
            cc: "cl"
            cxx: "cl"
            archiver: "7z a"
            generators: "Visual Studio 16 2019"
            build_dir: 'build'
          #- os: ubuntu-latest
          #  name: "Ubuntu GCC-11"
          #  artifact: "ubuntu_gcc.7z"
          #  build_type: "RelWithDebInfo"
          #  cc: "gcc-11"
          #  cxx: "g++-11"
          #  archiver: "7z a"
          #  generators: "Unix Makefiles"
          #  build_dir: 'build'
    steps:
      - name: Build
        id: build
        uses: Silverlan/common_actions/generic_build_workflow@actions
        
