name: Build
on: [push]
#on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  # WINDOWS x64 MSVC
  build-windows:
    name: Build-Windows-x64
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Windows x64 MSVC",
            os: windows-latest,
            artifact: "Windows-MSVC.tar.xz",
            build_type: "RelWithDebInfo",
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat",
            cc: "cl",
            cxx: "cl",
            archiver: "7z a",
            generators: "Visual Studio 16 2019",
            build_dir: 'build'
          }

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Initialize Env
        id: init-env
        uses: Silverlan/common_actions/set_common_env_vars@actions

      - name: Build
        id: build
        uses: Silverlan/util_image/github_actions/build@actions
          
      - uses: actions/upload-artifact@v2
        with:
          name: upload-binary
          path: "build/${{ matrix.config.build_type }}/util_image{{ env.GA_SHARED_LINK_LIBRARY_EXT }}"
